### ISSUE TITLE
Discuss skpm publish

### ISSUE THREAD

**Issue by mathieudutour** [naughtandcross/sketch-library-audit#1]
Hey :wave:

I just saw "After wrestling with skpm publish for a couple of nights, filed a PR manually to get this out.", and I was wondering what was the issues. I'd be happy to improve the process if possible :)

**Comment by naughtandcross** [comment]
Thanks for reaching out, basically hitting a similar issue to [skpm issue 156](https://github.com/skpm/skpm/issues/156). skpm publish gets perpetually stuck on "pushing the changes to git". I've tried all the suggestions there and from [this post on sketchplugins.com](https://sketchplugins.com/d/480-how-to-use-skpm-to-publish-a-plugin/8), but still no luck.

**Comment by naughtandcross** [comment]
Looks like 1.1.13 fixed my issue! Thanks @mathieudutour.
